language: java
jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c "create user bubblerise with password '123456';" -U postgres
  - psql -c "create database bubblerise;" -U postgres
  - psql -c "grant all on database bubblerise to bubblerise;" -U postgres

branches:
  only:
  - dev

deploy:
  provider: heroku
  api_key:
    secure: f0a29ee3-64f1-498d-8ec1-2a909777eaf3
  app: bubblerise-backend
  on:
    repo: java-park-mail-ru/Brainstorm-09-2017
    branch: dev
  skip_cleanup: true

install:
  - mvn clean install